on: [push, pull_request]
name: Go Test

jobs:
  unit:
    strategy:
      fail-fast: false
      matrix:
        os: [ "ubuntu", "windows", "macos" ]
        go: [ "1.16.x", "1.17.0-rc1" ]
    env:
      COVERAGES: ""
    runs-on: ${{ matrix.os }}-latest
    name: ${{ matrix.os}} (go ${{ matrix.go }})
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/setup-go@v2
        with:
          stable: 'false'
          go-version: ${{ matrix.go }}
      - name: Go information
        run: |
          go version
          go env
      - name: Run repo-specific setup
        uses: ./.github/actions/go-test-setup
        if: hashFiles('./.github/actions/go-test-setup') != ''
      - name: Run tests
        uses: protocol/multiple-go-modules@v1.2
        with:
          run: go test -v -coverprofile module-coverage.txt ./...
      - name: Run tests (32 bit)
        if: ${{ matrix.os != 'macos' }} # can't run 32 bit tests on OSX.
        uses: protocol/multiple-go-modules@v1.2
        env:
          GOARCH: 386
        with:
          run: go test -v ./...
      - name: Run tests with race detector
        if: ${{ matrix.os == 'ubuntu' }} # speed things up. Windows and OSX VMs are slow
        uses: protocol/multiple-go-modules@v1.2
        with:
          run: go test -v -race ./...
      - name: Collect coverage files
        shell: bash
        run: echo "COVERAGES=$(find . -type f -name 'module-coverage.txt' | tr -s '\n' ',' | sed 's/,$//')" >> $GITHUB_ENV
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@c585afe366f940d214dc09df2664c06d7fe07052 # v2.0.1
        with:
          files: '${{ env.COVERAGES }}'
          env_vars: OS=${{ matrix.os }}, GO=${{ matrix.go }}
